### ISSUE TITLE
Uncaught `param` syntax error

### ISSUE THREAD

**Issue by gyandeeps** [Constellation/doctrine#106]
When I try to use the library to parse this syntax it doesn't thow any error:

```js
/**
* @param fields [Array]
*/
function crashIt() {
     return "";
}
```

But for the below syntax it does throw an syntax error:

```js
/**
* @returns fields [Array]
*/
function crashIt() {
     return "";
}
```

Is the top `@param` syntax correct?

**Comment by jifeon** [comment]
You should place type before the name like this:
```js
/**
 * @param {Array} fields
 */
function crashIt() {
    return "";
}
```

[Here](http://usejsdoc.org/tags-param.html) you can read full documentation for `@param`, the same for [`@returns`](http://usejsdoc.org/tags-returns.html)
