### ISSUE TITLE
Issue with parsing `undefined` type in return

### ISSUE THREAD

**Issue by gyandeeps** [Constellation/doctrine#117]
For the following code:

```js
/**
* hi
* @param {string} abc parammmmm
* @returns {undefined}
*/
function test(abc){
    var x = abc + 1;
}
```

The `tag.type.name` for the `return` is returned as `undefined` but the expected results is not be `"undefined"`.

Same applies to `@returns {null}`. The `tag.type.name` for the `return` is returned as `undefined` but the expected results is not be `"null"`.

Eslint ref: https://github.com/eslint/eslint/issues/3382

**Comment by Constellation** [comment]
Could you explain why `name` field is needed?
We can recognize it by looking the `type` field. `name` field is only defined for `Syntax.NameExpression` and `Syntax.ParameterType` currently.

**Comment by gyandeeps** [comment]
You are right. I dont know why I was thinking in that direction.
